package main.enums;

public enum Buttons {
    BUTTON_START_NEW_GAME,
    BUTTON_CHANGE_GAME_LANGUAGE,
    BUTTON_MY_STATS,
    BUTTON_HELP,
    BUTTON_RUS,
    BUTTON_ENG,
    BUTTON_STOP,
    BUTTON_CHANGE_LANGUAGE,
    BUTTON_SELECT_MENU,
    BUTTON_DM
}