name: Deploy docker image

on:
  push:
    branches:
      - 'main'

jobs:

  build_docker_image:
    runs-on: ubuntu-20.04
    steps:

      #     Build JAR:
      - uses: actions/checkout@v1
      - name: set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 1.15
      - name: Maven Package
        run: mvn -B clean compile package -DskipTests

      #     Build Docker image:
      - name: Build and tag image
        run: |
          docker build -t megoru/hangman .
      #     Login to Docker Hub:
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image
        run: docker push megoru/hangman