name: Deploy docker image

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      #     Build Docker image:
      - name: Build and tag image
      run: |
      docker build -t megoru/hangman .
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_LOGIN }} | docker login -u ${{ secrets.DOCKER_PASSWORD }} --password-stdin