name: Deploy docker image

on:
  push:
    branches:
      - 'main'

jobs:

  build_docker_image:
    runs-on: ubuntu-18.04
    steps:
      #     Build Docker image:
      - name: Build and tag image
        run: |
          docker build -t megoru/hangman .
      #     Login to Docker Hub:
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image
        run: docker push megoru/hangman